#!/bin/sh
# Uses debian's uscan utility to download newer versions of ISOs when they become available.
# USCAN_OPTS=--debug ./uscan
# USCAN_OPTS=--force-download ./uscan

cd "$(dirname "$0")"

BIN=../bin

uscan_watch() {
	local package="${1%.watch}"
	local version=0
	if [ -f "$package.version" ]; then
		if [ -f "$BIN/$(cut -f2 $package.version)" ]; then
			version="$(cut -f1 $package.version)"
		fi
	fi
	export USCAN_PACKAGE="$package"
	uscan $USCAN_OPTS --no-symlink --upstream-version "$version" --package "$package" --watchfile "$package.watch" --download --pasv --destdir "$BIN"
}

case "$1" in
--upstream-version)
	echo "$2	$3" > "$USCAN_PACKAGE.version"
	;;
"")
	len=$(for i in *.watch; do echo "${#i}"; done | sort -n | tail -n1)
	for i in *.watch; do
		( prefix=$(printf "%--$((len - 6))s | " "${i%.watch}"); uscan_watch "$i" | sed -e "s/^/$prefix/" ) &
	done
	wait
	;;
*)
	if [ -f "$1" ]; then
		uscan_watch "$1"
	else
		exit 2
	fi
	;;
esac
