#!/bin/bash
# Uses debian's uscan utility to download newer versions of ISOs when they become available.
#
# Check for updates, but don't write anything:
#   ./uscan
# Download updates and update .version files
#   USCAN_OPTS=--force-download ./uscan
# Debug any problems:
#   USCAN_OPTS=--debug ./uscan

cd "$(dirname "$0")"

BIN="$(realpath "../bin")"

case "$USCAN_OPTS" in
*--download*)
	echo >&2 "$0: \"USCAN_OPTS=--download\" has no effect due to the way we run uscan, converting it to --force-download instead"
	USCAN_OPTS="${USCAN_OPTS/--download/--force-download}"
	;;
esac

uscan_watch() {
	local package="${1%.watch}"
	local version=0
	if [ -f "$package.version" ]; then
		if [ -f "$BIN/$(cut -f2 $package.version)" ]; then
			version="$(cut -f1 $package.version)"
		fi
	fi
	export USCAN_PACKAGE="$package" # for uscan's Update-Script functionality
	uscan $USCAN_OPTS --no-symlink --upstream-version "$version" --package "$package" --watchfile "$package.watch" --destdir "$BIN"
}

case "$1" in
--upstream-version)
	# called by uscan's Update-Script functionality, we set USCAN_PACKAGE earlier
	echo "$2	$3" > "$USCAN_PACKAGE.version"
	;;
"")
	len=$(for i in *.watch; do echo "${#i}"; done | sort -n | tail -n1)
	for i in *.watch; do
		( prefix=$(printf "%--$((len - 6))s | " "${i%.watch}"); uscan_watch "$i" | sed -e "s/^/$prefix/" ) &
	done
	wait
	;;
*)
	if [ -f "$1" ]; then
		uscan_watch "${1%.version}"
	else
		exit 2
	fi
	;;
esac
